### PR TITLE
Update Readme.md with suggestions for hosting the application on WCH.

### PR DESCRIPTION
**Pull request by mburati**
Update Readme.md with suggestions for hosting the application on WCH (additional optional note in step 1 and additional optional step 6).   @llpomerl and/or @jlidaka and/or @jbooth1 please review and these changes and let me know if the described steps work for you,  prior to merging this pull request.

### CODE REVIEW

**Comment by jlidaka** [comment]
Mike, are you sure your wiki syntax is correct? the replacement properties you have with <...> will cause issues if not formatted properly. I think you might need some quotes like this:

`<some replacement stuff>`

**Review by jbooth1 — COMMENTED** [review]
@mburati One comment - I would suggest that the app would get published in its own folder for the tenant, not at the root for the tenant.

**Comment by jbooth1** [comment]
@mburati One more thing - the sample JS has user credentials embedded, and the delivery URL of the published application (index.html) is publicly available. So I don't think we can recommend that developers push and publish the sample in that form. We should discuss offline.

**Comment by mburati** [comment]
Good point - lets hold on this pull request until we have a good answer for getting those out of there.

**Pull request closed without merging**
